name: A workflow for my Hello World file
on:
  - push
  - pull_request
jobs:
  build:
    name: Hello world action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: check
        run: pwd
      - name: check_how1
        run: git_hash=$(git rev-parse --short=8 "$GITHUB_SHA")
      - name: check_how2
        run: git rev-parse --short=8 HEAD
      - name: check2
        run: ls
      - name: update
        run: chmod +x dir/
      - name: copy file
        run: cp -r ./dir/ ./action-a/dir/
      - name: check3
        run: ls ./action-a/
      - uses: ./action-a
        with:
          MY_NAME: "Mona"
