name: A workflow for my Hello World file
on: push
jobs:
  build:
    name: Hello world action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: check
        run: pwd
      - name: check2
        run: ls
      - name: copy file
        run: ./entrypoint.sh ./action-a/entrypoint.sh
      - uses: ./action-a
        with:
          MY_NAME: "Mona"
