name: A workflow for my Hello World file
on: push
jobs:
  build:
    name: Hello world action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: check
        run: pwd
      - name: check2
        run: ls
      - name: update
        run: chmod +x dir/
      - name: copy file
        run: cp -r ./dir/ ./action-a/dir/
      - name: check3
        run: ls ./action-a/
      - uses: ./action-a
        with:
          MY_NAME: "Mona"
